/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thecsillags.choice;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

import com.google.common.collect.Lists;

public class LibraryTest {
    @Test public void testPlain() {
        final List<String> results = new ArrayList<>();
        final ChoiceRunner r = new ChoiceRunner();
        r.run((c) -> {
            results.add("" + c.chooseArg(0, 1) + "" + c.chooseArg(0, 1) + "" + c.chooseArg(0, 1));
        });

        final ArrayList<String> expected = Lists.newArrayList("000", "001", "010", "011", "100", "101", "110", "111");
        assertEquals(expected, results);
    }
}
