[package]
name = "chooser"
version = "0.1.0"
authors = ["Drew Csillag <drew@thecsillags.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "example"
test = false

[dependencies]
crossbeam = "0.8.2"
